# Generated by Django 3.2.9 on 2021-11-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
    ]
