# Generated by Django 3.2.9 on 2021-11-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gala', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Gala.category')),
                ('location', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Gala.location')),
            ],
        ),
    ]
