# Generated by Django 3.2.4 on 2021-11-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gala', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
